plugins {
    id 'java'
    id 'application'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

application {
    mainClass = 'Main'
    applicationDefaultJvmArgs = ['-Djava.awt.im.style=below-the-spot', '-Dfile.encoding=UTF-8']
}

repositories {
    mavenCentral()
}

dependencies {
    implementation files('lib/mysql-connector-j-8.4.0.jar')
    implementation 'com.google.code.gson:gson:2.10.1'
    compileOnly files('lib/lombok.jar')
    annotationProcessor files('lib/lombok.jar')
}
tasks.withType(JavaExec) {
    systemProperty "file.encoding", "UTF-8"
}
