bookSelectAll=SELECT * FROM book ORDER BY bookid
bookInsertOne=INSERT INTO book(bookname, publisher, price) VALUES(?,?,?)
bookUpdateOne=UPDATE book SET bookname=?, publisher=?, price=? WHERE bookid=?
bookDeleteOne=DELETE FROM book WHERE bookid=?
custSelectAll=SELECT * FROM customer ORDER BY custid
custInsertOne=INSERT INTO customer(name, address, phone) VALUES(?,?,?)
custUpdateOne=UPDATE customer SET name=?, address=?, phone=? WHERE custid=?
custDeleteOne=DELETE FROM customer WHERE custid=?
ordrSelectAll=SELECT o.orderid, c.custid, c.name, b.bookid, b.bookname, o.saleprice, o.orderdate FROM orders o, customer c, book b WHERE o.custid=c.custid AND o.bookid=b.bookid ORDER BY orderid
ordrInsertOne=INSERT INTO orders(custid, bookid, saleprice, orderdate) VALUES(?,?,?,curdate())
ordrUpdateOne=UPDATE orders SET custid=?, bookid=?, saleprice=? WHERE orderid=?
ordrDeleteOne=DELETE FROM orders WHERE orderid=?